Repository DeveloperAcademy-POSTECH/MacC-Team-EarthValley80, pull requests merged in 2022-10, with the labels that each got.

#2 [SETTING] 프로젝트 기초 세팅을 진행했습니다.
  EarthValley80/EarthValley80.xcodeproj/project.pbxproj
  EarthValley80/EarthValley80/Base.lproj/Main.storyboard
  EarthValley80/EarthValley80/Global/Extensions/NSObject+Extension.swift
  EarthValley80/EarthValley80/Global/Extensions/UIButton+Extension.swift
  EarthValley80/EarthValley80/Global/Extensions/UICollectionView+Extension.swift
  EarthValley80/EarthValley80/Global/Extensions/UIColor+Extension.swift
  EarthValley80/EarthValley80/Global/Extensions/UITableView+Extension.swift
  EarthValley80/EarthValley80/Global/Extensions/UIView+Extension.swift
  EarthValley80/EarthValley80/Global/Extensions/UIViewController+Extension.swift
  EarthValley80/EarthValley80/Global/Literals/ImageLiteral.swift
  EarthValley80/EarthValley80/Global/Literals/StringLiteral.swift
  EarthValley80/EarthValley80/Global/Resource/Assets.xcassets/AccentColor.colorset/Contents.json
  EarthValley80/EarthValley80/Global/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  EarthValley80/EarthValley80/Global/Resource/Assets.xcassets/Contents.json
  EarthValley80/EarthValley80/Global/Resource/Storyboard/Base.lproj/LaunchScreen.storyboard
  EarthValley80/EarthValley80/Global/Resource/Storyboard/MyNews.storyboard
  EarthValley80/EarthValley80/Global/Resource/Storyboard/News.storyboard
  EarthValley80/EarthValley80/Global/Resource/Storyboard/NewsFeed.storyboard
  EarthValley80/EarthValley80/Global/Supports/AppDelegate.swift
  EarthValley80/EarthValley80/Global/Supports/Info.plist
  EarthValley80/EarthValley80/Global/Supports/SceneDelegate.swift
  EarthValley80/EarthValley80/Global/Utils/UIView+Constraints.swift
  EarthValley80/EarthValley80/Global/Utils/UIViewController+Alert.swift
  EarthValley80/EarthValley80/Screen/MyNews/MyNewsViewController.swift
  EarthValley80/EarthValley80/Screen/News/NewsViewController.swift
  EarthValley80/EarthValley80/Screen/NewsFeed/NewsFeedViewController.swift
  EarthValley80/EarthValley80/ViewController.swift
Labels: 🎨 듀나, ⚙ Setting, 🫶🏻 ASAP

#16 [DOCS] yml 파일 실행 브랜치에 feature 브랜치를 추가합니다.
  .github/workflows/builder.yml
  .github/workflows/swiftlint.yml
Labels: 📃 Docs, 🫶🏻 ASAP, 🍋 듀나

#18 [ADD] Apple SD Gothic Neo 폰트를 Extension 파일로 추가합니다.
  EarthValley80/EarthValley80.xcodeproj/project.pbxproj
  EarthValley80/EarthValley80/Global/Extensions/UIFont+Extension.swift
Labels: ⚙ Setting, 🫶🏻 ASAP, 🍋 듀나

#20 [DOCS] 데일리 스크럼 이슈 탬플릿 양식에 표 형태를 추가했습니다.
  .github/ISSUE_TEMPLATE/earthvalley80-scrum.md
Labels: 📃 Docs, 🫶🏻 ASAP, 🐻 브라운

#13 [ADD] 뉴스 읽기 뷰(ReadingNewsViewController) 전체적인 레이아웃을 잡았습니다.
  EarthValley80/EarthValley80.xcodeproj/project.pbxproj
  EarthValley80/EarthValley80/Global/Extensions/UILabel+Extension.swift
  EarthValley80/EarthValley80/Global/Literals/StringLiteral.swift
  EarthValley80/EarthValley80/Global/Resource/Storyboard/News.storyboard
  EarthValley80/EarthValley80/Screen/News/Cells/NewsContentTableViewCell.swift
  EarthValley80/EarthValley80/Screen/News/Components/NewsTitleHeaderView.swift
  EarthValley80/EarthValley80/Screen/News/Components/QuestionView.swift
  EarthValley80/EarthValley80/Screen/News/ReadingNewsViewController.swift
Labels: 🖼 UI, 🫶🏻 ASAP, ▪️ News, 🍋 듀나

#25 [DOCS] .swiftlint.yml 파일을 추가했습니다.
  .swiftlint.yml
Labels: 📃 Docs, ⚙ Setting, 🍋 듀나

#26 [SETTING] Extension Color 값들을 추가합니다.
  EarthValley80/EarthValley80/Global/Extensions/UIColor+Extension.swift
Labels: ⚙ Setting, 🫶🏻 ASAP, 🍋 듀나

#23 [ADD] 제목 유추 뷰(TitleInferingViewController) 레이아웃을 설정했습니다.
  EarthValley80/EarthValley80.xcodeproj/project.pbxproj
  EarthValley80/EarthValley80/Global/Extensions/UITextView+Extension.swift
  EarthValley80/EarthValley80/Global/Literals/ImageLiteral.swift
  EarthValley80/EarthValley80/Global/Literals/StringLiteral.swift
  EarthValley80/EarthValley80/Global/Resource/Storyboard/News.storyboard
  EarthValley80/EarthValley80/Screen/News/Components/BackButton.swift
  EarthValley80/EarthValley80/Screen/News/Components/BlurredLabel.swift
  EarthValley80/EarthValley80/Screen/News/Components/NewsTitleHeaderView.swift
  EarthValley80/EarthValley80/Screen/News/Components/QuestionView.swift
  EarthValley80/EarthValley80/Screen/News/NewsViewController.swift
  EarthValley80/EarthValley80/Screen/News/ReadingNewsViewController.swift
  EarthValley80/EarthValley80/Screen/News/TitleInferingViewController.swift
Labels: 🖼 UI, 🫶🏻 ASAP, ▪️ News, 🍋 듀나

#28 [ADD] 가이드 뷰(NewsGuideViewController) 레이아웃을 설정했습니다.
  EarthValley80/EarthValley80.xcodeproj/project.pbxproj
  EarthValley80/EarthValley80/Global/Literals/ImageLiteral.swift
  EarthValley80/EarthValley80/Global/Literals/StringLiteral.swift
  EarthValley80/EarthValley80/Screen/News/Components/GuidingView.swift
  EarthValley80/EarthValley80/Screen/News/NewsGuideViewController.swift
  EarthValley80/EarthValley80/Screen/News/ReadingNewsViewController.swift
Labels: 🖼 UI, 🫶🏻 ASAP, ▪️ News, 🍋 듀나

#38 [ADD] 요모조모 뉴스 메인화면(YomojomoNewsViewController)의 레이아웃을 설정했습니다.
  EarthValley80/EarthValley80.xcodeproj/project.pbxproj
  EarthValley80/EarthValley80/Global/Extensions/Date+Extension.swift
  EarthValley80/EarthValley80/Global/Literals/StringLiteral.swift
  EarthValley80/EarthValley80/Global/UIComponent/MainTitleView.swift
  EarthValley80/EarthValley80/Network/Model/News.swift
  EarthValley80/EarthValley80/Screen/NewsFeed/NewsFeedViewController.swift
  EarthValley80/EarthValley80/Screen/YomojomoNews/Cells/YomojomoNewsTitleCollectionViewCell.swift
  EarthValley80/EarthValley80/Screen/YomojomoNews/YomojomoNewsViewController.swift
Labels: 🖼 UI, 🫶🏻 ASAP, ▪️ YomojomoNews, 🐻 브라운

#35 [FEAT] 기사 읽기 뷰에서 터치를 통해서 문장을 옮겨다니는 로직을 구현했습니다.
  EarthValley80/EarthValley80/Global/Extensions/UILabel+Extension.swift
  EarthValley80/EarthValley80/Global/Resource/Storyboard/News.storyboard
  EarthValley80/EarthValley80/Screen/News/Cells/NewsContentTableViewCell.swift
  EarthValley80/EarthValley80/Screen/News/ReadingNewsViewController.swift
Labels: ✨ Feature, 🫶🏻 ASAP, ▪️ News, 🍋 듀나

#37 [FEAT] 기사 50%를 읽었을 때, 버튼 활성화 및 질문 뷰 나오는 로직을 구현했습니다.
  EarthValley80/EarthValley80.xcodeproj/project.pbxproj
  EarthValley80/EarthValley80/Global/Literals/StringLiteral.swift
  EarthValley80/EarthValley80/Screen/News/Components/NextButton.swift
  EarthValley80/EarthValley80/Screen/News/Components/QuestionTitleStackView.swift
  EarthValley80/EarthValley80/Screen/News/Components/QuestionView.swift
  EarthValley80/EarthValley80/Screen/News/ReadingNewsViewController.swift
Labels: ✨ Feature, 👏 Improvement, 🫶🏻 ASAP, ▪️ News, 🍋 듀나

#42 [ADD] 앱 기본 세팅(아이콘, 앱 이름, bundle identifier)을 진행했습니다.
  EarthValley80/EarthValley80.xcodeproj/project.pbxproj
  EarthValley80/EarthValley80/Global/Resource/Assets.xcassets/AppIcon.appiconset/100.png
  EarthValley80/EarthValley80/Global/Resource/Assets.xcassets/AppIcon.appiconset/1024.png
  EarthValley80/EarthValley80/Global/Resource/Assets.xcassets/AppIcon.appiconset/114.png
  EarthValley80/EarthValley80/Global/Resource/Assets.xcassets/AppIcon.appiconset/120.png
  EarthValley80/EarthValley80/Global/Resource/Assets.xcassets/AppIcon.appiconset/144.png
  EarthValley80/EarthValley80/Global/Resource/Assets.xcassets/AppIcon.appiconset/152.png
  EarthValley80/EarthValley80/Global/Resource/Assets.xcassets/AppIcon.appiconset/167.png
  EarthValley80/EarthValley80/Global/Resource/Assets.xcassets/AppIcon.appiconset/180.png
  EarthValley80/EarthValley80/Global/Resource/Assets.xcassets/AppIcon.appiconset/20.png
  EarthValley80/EarthValley80/Global/Resource/Assets.xcassets/AppIcon.appiconset/29.png
  EarthValley80/EarthValley80/Global/Resource/Assets.xcassets/AppIcon.appiconset/40.png
  EarthValley80/EarthValley80/Global/Resource/Assets.xcassets/AppIcon.appiconset/50.png
  EarthValley80/EarthValley80/Global/Resource/Assets.xcassets/AppIcon.appiconset/57.png
  EarthValley80/EarthValley80/Global/Resource/Assets.xcassets/AppIcon.appiconset/58.png
  EarthValley80/EarthValley80/Global/Resource/Assets.xcassets/AppIcon.appiconset/60.png
  EarthValley80/EarthValley80/Global/Resource/Assets.xcassets/AppIcon.appiconset/72.png
  EarthValley80/EarthValley80/Global/Resource/Assets.xcassets/AppIcon.appiconset/76.png
  EarthValley80/EarthValley80/Global/Resource/Assets.xcassets/AppIcon.appiconset/80.png
  EarthValley80/EarthValley80/Global/Resource/Assets.xcassets/AppIcon.appiconset/87.png
  EarthValley80/EarthValley80/Global/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  EarthValley80/EarthValley80/Global/Supports/Info.plist
Labels: 🍋 듀나
